//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projetsv3
{
    using System;
    using System.Collections.Generic;
    
    public partial class evenement
    {
        public int id { get; set; }
        public string naam { get; set; }
        public string beschrijving { get; set; }
        public int locatie { get; set; }
        public System.DateTime datum { get; set; }
    
        public virtual gemeente gemeente { get; set; }
    }
}
