//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projetsv3
{
    using System;
    using System.Collections.Generic;
    
    public partial class persoon
    {
        public int id { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string street { get; set; }
        public int number { get; set; }
        public int gemeente_id { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public Nullable<int> Admin { get; set; }
        public Nullable<int> Organisator { get; set; }
        public string login { get; set; }
        public string password { get; set; }
    
        public virtual gemeente gemeente { get; set; }
    }
}
